<script lang="ts">
    import { onMount } from 'svelte';
    import type { PageData } from './$types'; // This is auto-generated by SvelteKit
    import { supabase } from '$lib/supabaseClient';
    import { format } from 'date-fns';

    interface Project {
        id: number;
        reference: string;
        name: string;
        application_type: string;
    }
    
    interface LoadingStatus {
        isLoading: boolean;
        progress: number;
        total: number | null;
    }

    // Interface definitions
    interface Document {
        id: number;
        project_id: number;
        title: string;
        file_size: string | null;
        document_url: string;
        publishing_organization: string;
        publication_date: string;
        stage: string;
        category: string;
        projects?: {
            name: string;
        };
        project?: {
            name: string;
        };
        project_name?: string;  // In case it's flattened
    }

    interface DocumentFilters {
        titleSearch: string;
        publisherSearch: string;
        selectedStages: Set<string>;
        selectedCategories: Set<string>;
        dateRange: {
            start: Date | null;
            end: Date | null;
        };
    }

    // Page data from loader
    export let data: PageData;

    // State management
    let isLoading = true;
    let error: string | null = null;
    let searchText = '';
    let selectedCategory = '';
    let selectedProjects = new Set<number>();
    let visibleProjects: Project[] = [];

    // State for documents section
    let isLoadingDocuments = false;
    let documents: Document[] = [];
    let filteredDocuments: Document[] = [];
    let stages: string[] = [];
    let categories: string[] = [];

    // Filter state
    let titleFilter = '';
    let publisherFilter = '';
    let selectedStages = new Set<string>();
    let selectedCategories = new Set<string>();
    let dateRange = {
        start: null as Date | null,
        end: null as Date | null
    };
    let showAdvancedOptions = false;


    // Initialize data when component mounts
    onMount(() => {
        try {
            if (!data.projects) {
                throw new Error('No projects data available');
            }
            visibleProjects = data.projects;
            isLoading = false;
        } catch (e) {
            error = e instanceof Error ? e.message : 'Failed to initialize projects';
            isLoading = false;
        }
    });

    // Filter projects based on search text and category
    $: {
        visibleProjects = data.projects.filter(project => {
            const matchesSearch = searchText === '' || 
                project.name.toLowerCase().includes(searchText.toLowerCase()) ||
                project.reference.toLowerCase().includes(searchText.toLowerCase());
            
            const matchesCategory = selectedCategory === '' || 
                project.application_type === selectedCategory;

            return matchesSearch && matchesCategory;
        });
    }

    // Distribute projects into three columns
    $: columns = distributeProjects(visibleProjects);

    function distributeProjects(projects: Project[]) {
        const columnCount = 3;
        const itemsPerColumn = Math.ceil(projects.length / columnCount);
        
        return Array.from({ length: columnCount }, (_, i) => 
            projects.slice(i * itemsPerColumn, (i + 1) * itemsPerColumn)
        );
    }


    $: if (selectedProjects.size > 0) {
        fetchDocuments(Array.from(selectedProjects));
    } else {
        documents = [];
        filteredDocuments = [];
    }

    // Selection handling functions
    function toggleProject(projectId: number) {
        if (selectedProjects.has(projectId)) {
            selectedProjects.delete(projectId);
        } else {
            selectedProjects.add(projectId);
        }
        selectedProjects = selectedProjects; // Trigger reactivity
    }

    function selectAll() {
        selectedProjects = new Set(data.projects.map(p => p.id));
    }

    function selectVisible() {
        visibleProjects.forEach(p => selectedProjects.add(p.id));
        selectedProjects = selectedProjects; // Trigger reactivity
    }

    function unselectAll() {
        selectedProjects.clear();
        selectedProjects = selectedProjects; // Trigger reactivity
    }


    // Fetch documents with verification
    async function fetchDocumentsWithVerification(projectIds: string[]) {
        console.log('Fetching documents for projects:', projectIds);

        try {
            // First, get the verification counts
            const { data: verificationData, error: verificationError } = await supabase
                .rpc('verify_project_documents', {
                    project_ids: projectIds
                });

            if (verificationError) {
                console.error('Verification error:', verificationError);
                return null;
            }

            console.log('Expected document counts:', verificationData);
            const totalExpectedDocuments = verificationData.reduce(
                (sum, project) => sum + Number(project.document_count), 0
            );

            // Fetch the actual documents
            const { data: documentsData, error } = await supabase
                .rpc('get_project_archived_documents', {
                    project_ids: projectIds
                });

            if (error) {
                console.error('Error fetching documents:', error);
                return null;
            }

            // Verify we got all documents
            const documentsByProject = new Map();
            documentsData.forEach(doc => {
                const count = documentsByProject.get(doc.project_id) || 0;
                documentsByProject.set(doc.project_id, count + 1);
            });

            console.log('Document counts by project:', Object.fromEntries(documentsByProject));
            console.log(`Received ${documentsData.length} of ${totalExpectedDocuments} expected documents`);

            // Check for any mismatches
            verificationData.forEach(project => {
                const receivedCount = documentsByProject.get(project.project_id) || 0;
                if (receivedCount !== project.document_count) {
                    console.warn(`Mismatch for project ${project.project_name}:`, {
                        expected: project.document_count,
                        received: receivedCount
                    });
                }
            });
            if (documentsData && documentsData.length > 0) {
                console.log('Sample document structure:', JSON.stringify(documentsData[0], null, 2));
            }

            return documentsData;
        } catch (error) {
            console.error('Error in document verification:', error);
            return null;
        }
    }

    async function fetchDocuments(projectIds: string[]) {
        if (projectIds.length === 0) {
            documents = [];
            filteredDocuments = [];
            return false;
        }

        isLoadingDocuments = true;
        try {
            const documentsData = await fetchDocumentsWithVerification(projectIds);
            
            if (documentsData) {
                documents = documentsData;
                stages = [...new Set(documentsData.map(doc => doc.stage))];
                categories = [...new Set(documentsData.map(doc => doc.category))];
                applyFilters();
                return true;
            }
            return false;
        } finally {
            isLoadingDocuments = false;
        }
    }

    // Modify the reactive statement to be more specific
    $: {
        const filterDependencies = [
            titleFilter,
            publisherFilter,
            selectedStages,
            selectedCategories,
            dateRange.start,
            dateRange.end
        ];
        if (documents.length > 0 && !isLoadingDocuments) {
            applyFilters();
        }
    }
    


    // Helper function to normalize text for searching
    function normalizeText(text: string): string {
        return text.toLowerCase().trim();
    }

    // Helper function to split search text into individual terms
    function getSearchTerms(searchText: string): string[] {
        return searchText
            .toLowerCase()
            .split(/\s+/)
            .filter(term => term.length > 0);
    }

    // Helper function to check if all search terms match the target text in any order
    function matchesAllTerms(targetText: string, searchTerms: string[]): boolean {
        if (!targetText) return false;
        const normalizedTarget = normalizeText(targetText);
        
        return searchTerms.every(term => {
            const wordMatch = new RegExp(`\\b${term}\\b`).test(normalizedTarget);
            if (wordMatch) return true;
            return normalizedTarget.includes(term);
        });
    }
   
    // // Watch for filter changes
    function applyFilters() {
        if (!documents || documents.length === 0) {
            filteredDocuments = [];
            return;
        }

        const titleTerms = getSearchTerms(titleFilter);
        const publisherTerms = getSearchTerms(publisherFilter);

        filteredDocuments = documents.filter(doc => {
            // Early returns for performance optimization
            if (titleTerms.length > 0 && !matchesAllTerms(doc.title, titleTerms)) {
                return false;
            }
            
            if (publisherTerms.length > 0 && !matchesAllTerms(doc.publishing_organization, publisherTerms)) {
                return false;
            }

            if (selectedStages.size > 0 && !selectedStages.has(doc.stage)) {
                return false;
            }

            if (selectedCategories.size > 0 && !selectedCategories.has(doc.category)) {
                return false;
            }

            if (dateRange.start && new Date(doc.publication_date) < dateRange.start) {
                return false;
            }

            if (dateRange.end && new Date(doc.publication_date) > dateRange.end) {
                return false;
            }

            return true;
        });
    }

    // Format date for display
    function formatDate(date: string): string {
        try {
            return format(new Date(date), 'dd/MM/yyyy');
        } catch {
            return 'Invalid date';
        }
    }
</script>

<!-- Loading State -->
{#if isLoading}
    <div class="flex justify-center items-center min-h-[200px]">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
    </div>
{:else if error}
    <!-- Error State -->
    <div class="p-4 bg-red-100 border border-red-400 text-red-700 rounded-md">
        <p>Error loading projects: {error}</p>
        <button 
            class="mt-2 px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors"
            on:click={() => window.location.reload()}
        >
            Retry
        </button>
    </div>
{:else}
    <!-- Main Content -->
    <div class="p-4 max-w-7xl mx-auto">
        <!-- Controls Section -->
        <!-- ... (rest of the template remains the same) ... -->
    </div>
{/if}
<div class="p-4 max-w-7xl mx-auto">
    <h1>Archived Project Documents</h1>
    <!-- Controls Section -->
    <div class="mb-6 space-y-4">
        <!-- Search and Category Filter -->
        <div class="flex gap-4">
            <input 
                type="text"
                bind:value={searchText}
                placeholder="Search projects..."
                class="flex-1 p-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
            <select
                bind:value={selectedCategory}
                class="p-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
                <option value="">All Categories</option>
                {#each data.applicationTypes as type}
                    <option value={type}>{type}</option>
                {/each}
            </select>
        </div>

        <!-- Selection Buttons -->
        <div class="flex gap-2 justify-between">
            <div class="flex gap-2">
                <button 
                    on:click={selectAll}
                    class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Select All
                </button>
                <button 
                    on:click={selectVisible}
                    class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Select Visible
                </button>
                <button 
                    on:click={unselectAll}
                    class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Unselect All
                </button>
            </div>
            <button
                class="px-4 py-2 bg-slate-300 text-white rounded-md hover:bg-blue-700 transition-colors justify-items-end"
            >
                <a href="/docrequest">
                    Missing documents?
                </a>
            </button>
        </div>
    </div>

    <!-- Projects Grid -->
    <div class="grid grid-cols-3 gap-4 mb-8 border rounded-lg p-2 bg-gray-50 max-h-[15vh] overflow-auto">
        {#each columns as column}
            <div class="space-y-2">
                {#each column as project}
                    <div
                        on:click={() => toggleProject(project.id)}
                        class="p-2 rounded-md cursor-pointer transition-colors"
                        class:bg-green-700={selectedProjects.has(project.id)}
                        class:text-white={selectedProjects.has(project.id)}
                        class:bg-white={!selectedProjects.has(project.id)}
                        class:text-slate-800={!selectedProjects.has(project.id)}
                        class:hover:bg-gray-100={!selectedProjects.has(project.id)}
                    >
                        <div class="font-medium">{project.name}</div>
                        <div class="text-sm opacity-75">{project.reference}</div>
                    </div>
                {/each}
            </div>
        {/each}
    </div>

    <div class="border rounded-lg p-4 bg-white">
        {#if selectedProjects.size === 0}
            <p class="text-gray-500 italic">Please select a project to get started</p>
        {:else if isLoadingDocuments}
            <div class="flex justify-center items-center p-8">
                <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
            </div>
        {:else}
            <!-- Document Filters -->
            <div class="mb-6 space-y-4">
                <!-- Full-width title filter -->
                <div class="w-full">
                    <input
                        type="text"
                        bind:value={titleFilter}
                        placeholder="Filter by title..."
                        class="w-full p-2 border rounded-md"
                    />
                </div>
        
                <!-- Collapsible Advanced Options -->
                <div class="border rounded-md bg-white">
                    <!-- Advanced Options Header -->
                    <button
                        on:click={() => showAdvancedOptions = !showAdvancedOptions}
                        class="w-full p-3 text-left flex justify-between items-center hover:bg-gray-50 border-b"
                    >
                        <span class="font-medium text-gray-700">Advanced Options</span>
                        <svg
                            class="w-5 h-5 transform transition-transform duration-200 text-gray-500 {showAdvancedOptions ? 'rotate-180' : ''}"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                        >
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                    </button>
        
                    {#if showAdvancedOptions}
                        <div class="p-4 space-y-6">
                            <!-- Top Row: Publisher Filter and Date Range -->
                            <div class="grid md:grid-cols-2 gap-4">
                                <!-- Publisher Filter -->
                                <div class="space-y-1">
                                    <label class="block text-sm font-medium text-gray-700">Uploading Party</label>
                                    <input
                                        type="text"
                                        bind:value={publisherFilter}
                                        placeholder="Filter by uploading party..."
                                        class="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
        
                                <!-- Date Range -->
                                <div class="space-y-1">
                                    <label class="block text-sm font-medium text-gray-700">Date Range</label>
                                    <div class="flex gap-2">
                                        <input
                                            type="date"
                                            bind:value={dateRange.start}
                                            class="flex-1 p-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                        />
                                        <input
                                            type="date"
                                            bind:value={dateRange.end}
                                            class="flex-1 p-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                        />
                                    </div>
                                </div>
                            </div>
        
                            <!-- Bottom Row: Stage and Category Multiselect -->
                            <div class="grid md:grid-cols-2 gap-4">
                                <!-- Stages -->
                                <div class="space-y-1">
                                    <label class="block text-sm font-medium text-gray-700">Stages</label>
                                    <div class="border rounded-md p-2 overflow-y-auto max-h-60">
                                        {#each stages as stage}
                                            <label class="flex items-center space-x-2 py-1 px-2 hover:bg-gray-50 rounded">
                                                <input
                                                    type="checkbox"
                                                    checked={selectedStages.has(stage)}
                                                    on:change={() => {
                                                        if (selectedStages.has(stage)) {
                                                            selectedStages.delete(stage);
                                                        } else {
                                                            selectedStages.add(stage);
                                                        }
                                                        selectedStages = selectedStages;
                                                    }}
                                                    class="rounded text-blue-600 focus:ring-blue-500"
                                                />
                                                <span class="text-gray-700">{stage}</span>
                                            </label>
                                        {/each}
                                    </div>
                                </div>
        
                                <!-- Categories -->
                                <div class="space-y-1">
                                    <label class="block text-sm font-medium text-gray-700">Categories</label>
                                    <div class="border rounded-md p-2 overflow-y-auto max-h-60">
                                        {#each categories as category}
                                            <label class="flex items-center space-x-2 py-1 px-2 hover:bg-gray-50 rounded">
                                                <input
                                                    type="checkbox"
                                                    checked={selectedCategories.has(category)}
                                                    on:change={() => {
                                                        if (selectedCategories.has(category)) {
                                                            selectedCategories.delete(category);
                                                        } else {
                                                            selectedCategories.add(category);
                                                        }
                                                        selectedCategories = selectedCategories;
                                                    }}
                                                    class="rounded text-blue-600 focus:ring-blue-500"
                                                />
                                                <span class="text-gray-700">{category}</span>
                                            </label>
                                        {/each}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {/if}
                </div>
            </div>
                
            <!-- Document List -->
            <div class="space-y-4">
                {#each filteredDocuments as doc}
                    <div class="border-b pb-3">
                        <div class="flex justify-between items-start">
                            <div class="flex-grow">
                                {#if doc.document_url}
                                    <a href={doc.document_url} target="_blank" rel="noopener noreferrer" 
                                    class="font-bold text-blue-600 hover:underline">
                                        {doc.title}
                                    </a>
                                {:else}
                                    <span class="font-bold">{doc.title} (URL error)</span>
                                {/if}
                                {#if doc.file_size}
                                    <span class="ml-2 text-gray-600">({doc.file_size})</span>
                                {/if}
                                {#if selectedProjects.size > 1}
                                    <span class="ml-2 text-gray-600">- {
                                        doc.projects?.name || 
                                        doc.project?.name || 
                                        doc.project_name || 
                                        'Unknown Project'
                                    }</span>
                                {/if}
                            </div>
                        </div>
                        <div class="flex justify-between mt-1 text-sm text-gray-600">
                            <span>From: {doc.publishing_organization}</span>
                            <span>Date: {formatDate(doc.publication_date)}</span>
                        </div>
                        <div class="mt-1 text-sm text-gray-600">
                            {doc.stage} - {doc.category}
                        </div>
                    </div>
                {/each}
                
                {#if filteredDocuments.length === 0}
                    <p class="text-gray-500 italic">No documents match the current filters</p>
                {/if}
            </div>
        {/if}
    </div>
</div>